// resources/laravel/js/components/ExampleComponent.vue
<template>
  <div class="container">
    <div class="row justify-content-center" @click="test" :key="test">
      <div class="col-md-8">
        <div class="card card-default">
          <div class="card-header">Example Component</div>

          <div class="card-body">I'm an example component.</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  mounted() {
    console.log("Component mounted.");
  }
};
</script>

// resources/js/components/react-example/index.js
import React from 'react';
import ReactDOM from 'react-dom';

function ReactExample() {
    return (
        <div className="container app-container">
            <div className="row">
                <div className="col-md-8">
                    <div className="card">
                        <div className="card-header">React Example Component</div>

                        <div className="card-body">I'm a React example component!</div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default ReactExample;

if (document.getElementById('react-example')) {
    ReactDOM.render(<ReactExample />, document.getElementById('react-example'));
}
